distSpecVersion: "1.1.1"

storage:
  rootDirectory: /var/lib/zot
  gc: true
  gcDelay: "1h"
  gcInterval: "24h"
  retention:
    delay: "24h"
    policies:
      - repositories: ["**/mirror/**"]
        deleteReferrers: false
        deleteUntagged: true
        keepTags:
          - pulledWithin: "720h"  # 30 days
  dedupe: true

http:
  address: "0.0.0.0"
  port: "5000"

log:
  level: "info"

extensions:
  sync:
    enable: true
    registries:
      - urls: ["https://docker.io"]
        onDemand: true
        maxRetries: 10
        retryDelay: "30s"
        tlsVerify: true
        content:
          - prefix: "**"
            destination: "/mirror/docker-io"

      - urls: ["https://oci.stackable.tech", "https://docker.stackable.tech"]
        onDemand: true
        maxRetries: 10
        retryDelay: "30s"
        tlsVerify: true
        content:
          - prefix: "**"
            destination: "/mirror/stackable"

      - urls: ["https://quay.io"]
        onDemand: true
        maxRetries: 10
        retryDelay: "30s"
        tlsVerify: true
        content:
          - prefix: "**"
            destination: "/mirror/quay"

  search:
    enable: true
    "cve":
      "updateInterval": "2h"

  ui:
    enable: true

  metrics:
    enable: true
    prometheus:
      path: "/metrics"
